### ISSUE TITLE
Bug in the example

### ISSUE THREAD

**Issue by thomasfrobieter** [viralpatel/jquery.shorten#24]
Your Example shows:
$(element).shorten({
    showChars: '50',
});

it should be:

$(element).shorten({
    showChars: 50,
});

**Comment by Dynamo6** [comment]
Thanks Thomas - that was driving me crazy!

**Comment by holtkamp** [comment]
Maybe provide a Pull Request with this minor but annoying change?

**Comment by Dynamo6** [comment]
@holtkamp Done :)
